services:
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    image: akil021/snaplink-config-server
    ports:
      - "8888:8888"
    networks:
      - snaplink-network
    environment:
      - GIT_USERNAME=AkileswarKrishnasamy
      - GIT_TOKEN=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
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    image: akil021/snaplink-discovery-server
    ports:
      - "8761:8761"
    networks:
      - snaplink-network
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - CONFIG_SERVER_URI=http://config-server:8888
      - CONFIG_FAIL_FAST=true
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  url-service:
    build:
      context: ./url-service
      dockerfile: Dockerfile
    image: akil021/snaplink-url-service
    ports:
      - "8001:8001"
    networks:
      - snaplink-network
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      - CONFIG_SERVER_URI=http://config-server:8888
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: akil021/snaplink-api-gateway
    ports:
      - "8081:8081"
    networks:
      - snaplink-network
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      - CONFIG_SERVER_URI=http://config-server:8888
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka

networks:
  snaplink-network:
    driver: bridge
