spring.application.name=api-gateway

spring.config.import=optional:configserver:http://localhost:8888

spring.cloud.gateway.mvc.routes[0].id=url-route
spring.cloud.gateway.mvc.routes[0].uri=lb://url-service
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/url/**